FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
RUN useradd -m appuser

COPY ./source/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./source/server.py .
USER appuser

EXPOSE 1502/tcp
ENV BACKEND_PORT=1502

CMD ["python","/app/server.py","--port","1502"]
