services:
  cache_point:
    build: .
    image: ctfae-ad:cache_point
    ports:
      - "6000:6000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    command: redis-server --maxmemory 500mb --maxmemory-policy allkeys-lfu
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
    mem_limit: 500M
    restart: always

volumes:
  redis_data:
