[general]

host = "0.0.0.0"
port = 5432
admin_username = "pgcat"
admin_password = "pgcat"
enable_prometheus_exporter = false
worker_threads = 2

[pools.note_checker.users.0]
username = "postgres"
password = "postgres"
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"
query_parser_enabled = false
idle_timeout = 300


[pools.note_checker.shards.0]
servers = [
  ["db", 5432, "primary"]
]
database = "note_hub"
